// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIGUQ6d0eawrh7uKhZCP4O4NIwAQPJn1c',
    appId: '1:631178187130:web:759cee4ab4e851043a06c3',
    messagingSenderId: '631178187130',
    projectId: 'kanban-lite-38aea',
    authDomain: 'kanban-lite-38aea.firebaseapp.com',
    storageBucket: 'kanban-lite-38aea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9MNH9sN5ufAC-NmGK5ENmMhL4p_bb5k0',
    appId: '1:631178187130:android:1aa675152130fb703a06c3',
    messagingSenderId: '631178187130',
    projectId: 'kanban-lite-38aea',
    storageBucket: 'kanban-lite-38aea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfWmjK-fpV46VZjnlKN8BPsPz_5XQn9ug',
    appId: '1:631178187130:ios:d71cd80a191ef7803a06c3',
    messagingSenderId: '631178187130',
    projectId: 'kanban-lite-38aea',
    storageBucket: 'kanban-lite-38aea.firebasestorage.app',
    iosBundleId: 'com.example.kanbanLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfWmjK-fpV46VZjnlKN8BPsPz_5XQn9ug',
    appId: '1:631178187130:ios:d71cd80a191ef7803a06c3',
    messagingSenderId: '631178187130',
    projectId: 'kanban-lite-38aea',
    storageBucket: 'kanban-lite-38aea.firebasestorage.app',
    iosBundleId: 'com.example.kanbanLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIGUQ6d0eawrh7uKhZCP4O4NIwAQPJn1c',
    appId: '1:631178187130:web:332eeffd3fd407d43a06c3',
    messagingSenderId: '631178187130',
    projectId: 'kanban-lite-38aea',
    authDomain: 'kanban-lite-38aea.firebaseapp.com',
    storageBucket: 'kanban-lite-38aea.firebasestorage.app',
  );
}
